version: '3.8'

services:
  snaplink-postgres-database:
    image: postgres:15
    container_name: snaplink-postgres-database
    restart: always
    environment:
      POSTGRES_USER: snaplink
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: snaplink
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/schemas/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "35432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U snaplink -d snaplink" ]
      interval: 10s
      timeout: 5s
      retries: 5

  snaplink-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: snaplink-service
    container_name: snaplink-service
    restart: unless-stopped
    depends_on:
      snaplink-postgres-database:
        condition: service_healthy
    environment:
      DB_CONNECTION: postgres://snaplink:${POSTGRES_PASSWORD}@snaplink-postgres-database:5432/snaplink
    ports:
      - "8080:8080"

  snaplink-telegram-bot:
    build:
      context: ./telegram
      dockerfile: Dockerfile
    image: snaplink-telegram-bot
    container_name: snaplink-telegram-bot
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - snaplink-service

volumes:
  postgres_data:
